### ISSUE TITLE
Tracking list: external extensions broken by release 3.4

### ISSUE THREAD

**Issue by oprypin** [Python-Markdown/markdown#1277]
Extensions broken by #1260:

* [x] [mdx_gh_links](https://pypi.org/project/mdx_gh_links/)
  https://github.com/Python-Markdown/github-links/issues/10
* [x] [mdx_truly_sane_lists](https://pypi.org/project/mdx-truly-sane-lists/)
  https://github.com/radude/mdx_truly_sane_lists/issues/11
* [x] [markdown_include](https://pypi.org/project/markdown-include/)
  https://github.com/cmacmackin/markdown-include/issues/33
* [x] [plantuml-markdown](https://pypi.org/project/plantuml-markdown/)
  https://github.com/mikitex70/plantuml-markdown/issues/67
* [x] [mdx_include](https://pypi.org/project/mdx-include/)
  https://github.com/neurobin/mdx_include/issues/7
* [ ] [lightgallery](https://pypi.org/project/lightgallery/)
  https://github.com/g-provost/lightgallery-markdown/issues/12
* [ ] featherlight
  https://github.com/it-novum/mkdocs-featherlight
* [ ] [fontawesome_markdown](https://pypi.org/project/fontawesome-markdown/)
  https://github.com/bmcorser/fontawesome-markdown/issues/17
* [ ] mkdcomments
  https://github.com/ryneeverett/python-markdown-comments/issues/7
* [ ] mkautodoc
  https://github.com/tomchristie/mkautodoc/pull/33

Other projects that aren't purely extensions:

* [ ] [pweave](https://pypi.org/project/Pweave/)
  https://github.com/mpastell/Pweave/pull/167
* [ ] [cmdtest](http://git.liw.fi/cgi-bin/cgit/cgit.cgi/cmdtest/)
  https://salsa.debian.org/python-team/packages/cmdtest/-/blob/master/debian/patches/0001-Fix-for-new-version-of-markdown.patch

(Checkmark means that a fix is released)
I'll keep this list updated as I become aware of more.

See also: [instructions for MkDocs](https://github.com/mkdocs/mkdocs/issues/2892#issuecomment-1188275760) - feel free to post there.

**Comment by facelessuser** [comment]
Can ask what the purpose of this issue is? What is the actionable item being requested?

Hmm...I guess Python Markdown doesn't have discussions enabled...that would probably be a more appropriate place for this...

**Comment by oprypin** [comment]
For tracking and for decision-making [for myself](https://github.com/mkdocs/mkdocs/issues/2892#issuecomment-1187999343) and possibly for this repo too. I could've opened it on mkdocs repo but it's not about mkdocs.
It's nice as an issue because of GitHub's autolinking and formatting.

**Comment by oprypin** [comment]
I am using these searches to find more:

* https://github.com/search?q=markdown_extensions+%223.4%22&type=Issues
* https://github.com/search?q=a767b2daaad78ba32d45a4f1dabb7c5e218f030a&type=issues

**Comment by tsibley** [comment]
@oprypin also https://github.com/ryanfox/sphinx-markdown-tables/issues/36

**Comment by oprypin** [comment]
OK, at this point I pretty much think that these breakages should not have happened in this way. The list of known breakages certainly already seems much bigger than expected.

I was trying to see how the community (mainly MkDocs) can deal with this, advocating for fixes, accepting to have to help users by pointing into the right place to report issues...  But anyway I have been [convinced](https://github.com/mkdocs/mkdocs/issues/2892#issuecomment-1188611444) that MkDocs can't take any reasonable step other than just preventing people from installing this newer version of Python-Markdown. Because indeed to non-technical users it will always just look like MkDocs is broken.

I was trying to argue that I don't want to just [punt this into the future](https://github.com/mkdocs/mkdocs/issues/2892#issuecomment-1188651875), but it seems like I'll have to do just that.

---

> Can ask what the purpose of this issue is? What is the actionable item being requested?

I have to admit that part of the purpose was collecting data to be able to write this message...
And what's actionable is reconsidering the rollout of these breakages.

**Comment by waylan** [comment]
I haven't looked at the individual extensions to see what broke (nor do I have the time to go look through them all). However, I do know that the we [removed support for a number of previously deprecated items][1] in the 3.4 release. The thing is, those deprecations have been in place since version 3.0 released on 2018-09-21. In other words, the developers of the various (now broken) extensions have been ignoring deprecation warnings for the last ~3.75 years. I think we gave everyone plenty of warning.

That said, of there is anything we broke which is not related to those deprecations, please point them out. 

[1]: https://python-markdown.github.io/change_log/release-3.4/#previously-deprecated-objects-have-been-removed

**Comment by mitya57** [comment]
What I have seen is related to deprecated items, yes. I agree that it was plenty of time.

**Comment by oprypin** [comment]
> the developers of the various (now broken) extensions have been ignoring deprecation warnings for the last ~3.75 years

I think the main issue is that there were actually no warnings whatsoever.

The website of MkDocs itself, which surely you must have updated within those last ~3.75 years, supposedly would've shown a warning every time it's built, because it has been relying on [Python-Markdown/github-links](https://github.com/Python-Markdown/github-links) (yes, within this same organization), which did not get updated until I [pointed it out yesterday](https://github.com/Python-Markdown/github-links/issues/10).

**Comment by mitya57** [comment]
Problem is that Python does not show DeprecationWarnings by default, unless you enable [development mode](https://docs.python.org/3/library/devmode.html#devmode).

**Comment by waylan** [comment]
@mitya57 is correct. The warnings were being issued, it's just that by default Python silenced them. Unfortunately there is nothing we can do to change that. Each user/developer needs to set up their own system to alert them of such warnings.

First of all, all of the deprecations were clearly identified in the release notes, so they should be of no surprise to anyone who reads them. I had intended to remove the code deprecated in 3.0 in 3.1 but held off because I recognized that most developers hadn't updated their extensions yet. In fact, in #1260 were the code was removed, I questioned whether we might want to raise some sort of Deprecation Error because I recognized that it was very likely that this would break many extensions. At least an error would clue them into why. But the decision was made to not do so as that would be unconventional.

@oprypin I'm sure you are not suggesting that we never remove deprecated code because Python has set a default we don't agree with.  After all, that would be ridiculous. I understand you are frustrated, but we have been more than accommodating by waiting 3.75 years and 4 point releases to remove the deprecated code.

Again, if there are any issues which are not related to the long overdue removal of deprecated code, I am open to discuss them in a new issue. However, we have done everything we reasonably can to warn people of the coming deprecations. Therefore, I am closing this issue as it is not actionable. That said, if anyone has constructive suggestions for any ways to improve in how we communicate deprecations in the future, please feel free to continue the discussion here. However, arguments over past decisions will result in a user either being banned and/or the conversation being locked as the Python-Markdown development team deems appropriate.

**Comment by stickgrinder** [comment]
Don't know if it's worth commenting here about this, but I just sent [this PR](https://github.com/bmcorser/fontawesome-markdown/pull/20) which fixes the problem for `fontawesome-markdown`.
